name: flutter_task_planner_app

description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  bezier_chart: ^1.0.16
  flutter_calendar_carousel: ^1.5.2
  google_maps_flutter: ^0.5.19+2
  fluttertoast: ^7.1.6
  crypto: ^2.1.5
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  custom_progress_dialog: ^1.0.5
  permission: ^0.1.7

  # Check that you have this dependency (added in the previous step)
  firebase_core: ^0.7.0

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  firebase_messaging: ^8.0.0-dev.14
  geolocator: 3.0.0               # AndroidX - Breaking!
  google_api_availability: 1.0.6  # Geolocator Dependency.
  flutter_polyline_points: ^0.1.0
  overlay_support: ^1.0.5
  app_settings: ^4.0.4

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/Logo bikem.png"
  image_path_android: "assets/images/Logo bikem.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  